### ISSUE TITLE
Sort & filter client cards

### ISSUE THREAD

**Issue by devlarabar** [devlarabar/100freelancers#12]
These three buttons on the top left of the home page are currently non-functional:

![Screenshot 2023-09-19 123910](https://github.com/devlarabar/100freelancers/assets/122644200/0a7d8299-7c92-42b1-be13-40acee471d33)

This issue specifically refers to adding the functionality of the first two, **sort** and **filter**.

**Comment by AhmedHHamdy** [comment]
I'll take this
