### ISSUE TITLE
Landing Page Design & Construction

### ISSUE THREAD

**Issue by devlarabar** [devlarabar/100freelancers#20]
It's time to start building our landing page! We need to both design and code the landing page (on the root route). Since users cannot see the features of the app without being logged in, it would be helpful to include screenshots and descriptions of the various features (and upcoming features) in the landing page to encourage new users to create accounts.

The screenshots should include desktop, tablet, and mobile views to display that the app works well on all screen sizes. Since the app is still in the early stages of development, placeholder images will work fine for now. [This](https://placehold.co/) is a great website for placeholders.

A small blurb describing the importance of freelancing for the start of a developer's tech career would be helpful as well!

Discussions regarding the design can be held here or in our thread on Discord.

**Comment by Kirk-Esterline** [comment]
I'd like to participate in building the landing page.

**Comment by rachel-rice** [comment]
I'm new to the project but would like to contribute to the landing page

**Comment by AhmedHHamdy** [comment]
I want to join in building the landing page :)

**Comment by XakHD** [comment]
I want to contribute :)

**Comment by ka-lange** [comment]
Here's the initial design for the landing page so far. On desktop, it should be a single page that doesn't scroll and on mobile, the screenshots can swipe scroll like you'd see in an App Store. 

I can help out more with making the Screenshots and graphics if we need and I'll add the logo files as soon as possible!
![image](https://github.com/devlarabar/100freelancers/assets/112651523/71917755-70d3-4f7c-a1bf-c73d99bf38f0)

**Comment by Kirk-Esterline** [comment]
Karissa if you are able to grab the screenshots that would be great! My plan is to have the basic structure of the page done by this time tomorrow.

**Comment by ka-lange** [comment]
Some Screenshots you can use:
<img width="441" alt="Screenshot 2023-11-02 at 11 01 20 AM" src="https://github.com/devlarabar/100freelancers/assets/112651523/11964e27-ba55-45e0-ad9d-34605f6416b0">
<img width="338" alt="Screenshot 2023-11-02 at 11 07 34 AM" src="https://github.com/devlarabar/100freelancers/assets/112651523/4616fa59-4e2a-431f-9f05-1c8e66c2a86e">

<img width="1116" alt="Screenshot 2023-11-02 at 11 03 17 AM" src="https://github.com/devlarabar/100freelancers/assets/112651523/ca7935c1-98aa-431b-b351-369aa0469fdb">
<img width="1128" alt="Screenshot 2023-11-02 at 11 03 44 AM" src="https://github.com/devlarabar/100freelancers/assets/112651523/01f413c2-66e2-4e63-a929-14b954068ecf">

Logo for landing page (I'm trying to make this a transparent PNG soon):
![logoDark](https://github.com/devlarabar/100freelancers/assets/112651523/b6c8789b-f6a9-4b55-a38d-6f45be26d6c8)

**Comment by ka-lange** [comment]
Logo SVG (this will be way crisper)
![darkLogo](https://github.com/devlarabar/100freelancers/assets/112651523/636a6351-998f-45a5-81b1-e6643f3347f2)
