### ISSUE TITLE
Finish creating the "Outreach" form

### ISSUE THREAD

**Issue by devlarabar** [devlarabar/100freelancers#4]
The "Outreach" form (`/client/app/outreach/add/page.jsx`) needs to be completed. It has already been started and currently looks like this:
![Screenshot 2023-09-12 140711](https://github.com/devlarabar/100freelancers/assets/122644200/04166282-d9a2-4534-b300-7a4c7d75fb18)

The remaining form fields should reflect the "Outreach" model.

**Comment by Kirk-Esterline** [comment]
I would like to tackle finishing this.

**Comment by vazquezea96** [comment]
Hi happy to help
